#
# Denyhosts Tasks
#
---
- yum: pkg=${item} state=installed
  with_items:
  - denyhosts
  tags:
  - denyhosts.pkgs

- template: src=${item} dest=/etc/denyhosts.conf owner=root group=root mode=0600
  first_available_file:
  - ${playbook_templates_private}/${playbook}/denyhosts.conf.j2-${ansible_fqdn}
  - ${playbook_templates_private}/${playbook}/denyhosts.conf.j2-${host_group}
  - ${playbook_templates_private}/${playbook}/denyhosts.conf.j2-${datacentre}
  - ${playbook_templates_private}/${playbook}/denyhosts.conf.j2
  - ${playbook_templates}/${playbook}/denyhosts.conf.j2-${ansible_fqdn}
  - ${playbook_templates}/${playbook}/denyhosts.conf.j2-${host_group}
  - ${playbook_templates}/${playbook}/denyhosts.conf.j2-${datacentre}
  - ${playbook_templates}/${playbook}/denyhosts.conf.j2
  tags:
  - denyhosts.cfg
